### ISSUE TITLE
Extreme.handle_info :tcp_closed exception after kill -9

### ISSUE THREAD

**Issue by revati** [exponentially/extreme#6]
Its on a `deleted_stream_subscription_fix` branch

```
[error] GenServer EventStore terminating
** (FunctionClauseError) no function clause matching in Extreme.handle_info/2
    (extreme) lib/extreme.ex:143: Extreme.handle_info({:tcp_closed, #Port<0.14560>}, %{credentials: %{pass: "changeit", user: "admin"}, pending_responses: %{}, received_data: "", should_receive: nil, socket: #Port<0.14560>, subscriptions: %{}, subscriptions_sup: #PID<0.350.0>})
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:tcp_closed, #Port<0.14560>}
State: %{credentials: %{pass: "changeit", user: "admin"}, pending_responses: %{}, received_data: "", should_receive: nil, socket: #Port<0.14560>, subscriptions: %{}, subscriptions_sup: #PID<0.350.0>}
[error] GenServer #PID<0.350.0> terminating
** (FunctionClauseError) no function clause matching in Extreme.handle_info/2
    (extreme) lib/extreme.ex:143: Extreme.handle_info({:tcp_closed, #Port<0.14560>}, %{credentials: %{pass: "changeit", user: "admin"}, pending_responses: %{}, received_data: "", should_receive: nil, socket: #Port<0.14560>, subscriptions: %{}, subscriptions_sup: #PID<0.350.0>})
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.349.0>, {:function_clause, [{Extreme, :handle_info, [{:tcp_closed, #Port<0.14560>}, %{credentials: %{pass: "changeit", user: "admin"}, pending_responses: %{}, received_data: "", should_receive: nil, socket: #Port<0.14560>, subscriptions: %{}, subscriptions_sup: #PID<0.350.0>}], [file: 'lib/extreme.ex', line: 143]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 615]}, {:gen_server, :handle_msg, 5, [file: 'gen_server.erl', line: 681]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
State: {:state, {#PID<0.350.0>, Extreme.SubscriptionsSupervisor}, :simple_one_for_one, [{:child, :undefined, Extreme.Subscription, {Extreme.Subscription, :start_link, [#PID<0.349.0>]}, :temporary, 5000, :worker, [Extreme.Subscription]}], :undefined, 3, 5, [], Extreme.SubscriptionsSupervisor, #PID<0.349.0>}
```

**Comment by revati** [comment]
Did you had time to look into this?

**Comment by mjaric** [comment]
Hi Revati,

Your Supervisor should handle this. We don't want to prejudice what should happen if connection is lost to EventStore, that is why we are "letting it to crash"

The question which you should ask your self is what do you want to do to the rest of genservers/subscriptions when connection is closed? In many cases you want to start over and that is why we suggest that supervisor should take care about child processes in such case.

Let it crash :)

Let me know if this is ok in your case.

**Comment by revati** [comment]
Yeah, thats how it should work, but it is not crashing because of that reason, but because there is not implemented method :? 
Wouldn't it be better to implement handler for such case and just raise error with nice message?

**Comment by burmajam** [comment]
We didn't want to just repack error. The only reason we are considering that solution is because of credentials in propagated message are exposed to log. Would you like to make PR how you think that should work?

**Comment by burmajam** [comment]
Hey, revati. Can you please try master branch version for fix of this no matching error?

**Comment by revati** [comment]
It's good :)
